version: '3'

services:
  api-estimate-gas:
    image: adminesollab/dev-repository:api-estimate-gas-latest
    env_file:
      - .env
    container_name: api-estimate-gas
    build: ./
    restart: always
    ports:
      - '4000:4000'
